/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-05-11 05:14:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dailyMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1618292427000L));
    _jspx_dependants.put("jar:file:/C:/Users/eb10/Desktop/취업반/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel_user/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612259905063L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>호텔JAVA</title>\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\" >\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Train+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 구글 폰트 한글 -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Single+Day&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("@font-face{\r\n");
      out.write("\tfont-family: 'Ubuntu', sans-serif, 'Noto Sans KR', sans-serif;\r\n");
      out.write("\tunicode-range:U+0041-005A, U+0061-007A,\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 헤더 파일 -->\r\n");
      out.write("<div class=\"nav\">\r\n");
      out.write("\t<div class=\"nav-inner\">\r\n");
      out.write("\t\t<div class=\"nav-content-wrapper\" id=\"headerWidth\">\r\n");
      out.write("\t\t\t<div class=\"content-left\">\r\n");
      out.write("\t\t\t\t<div class=\"hotel-logo\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">JAVA</a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content-right\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<img id=\"open_submenu\" height=\"40px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/main-subMenu.png\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal-login hidden\">\r\n");
      out.write("\t<div class=\"modal_content\">\r\n");
      out.write("\t\t<!--표시하고 싶은 내용-->\r\n");
      out.write("\t\t<!-- 로그인 안 했을 때 -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인 했을 때 -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tconst open_submenu = document.getElementById('open_submenu');\r\n");
      out.write("\tconst close_submenu = document.getElementById('close_submenu');\r\n");
      out.write("\tconst modal = document.querySelector('.modal-login');\r\n");
      out.write("\t\r\n");
      out.write("\topen_submenu.onclick = function() {\r\n");
      out.write("\t\tmodal.classList.remove('hidden');\r\n");
      out.write("\t\t$(\"html, body\").addClass(\"not_scroll\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tclose_submenu.onclick = function() {\r\n");
      out.write("\t\tmodal.classList.add('hidden');\r\n");
      out.write("\t\t$(\"html, body\").removeClass(\"not_scroll\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 주소에따라 헤더 넓이 조절 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar link = document.location.pathname;\r\n");
      out.write("\tvar mainAddress = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/';\r\n");
      out.write("\tvar nav = document.getElementById('headerWidth');\r\n");
      out.write("\tvar modalLogin = document.querySelector('.modal-login');\r\n");
      out.write("\t\r\n");
      out.write("\tif(link != mainAddress){\r\n");
      out.write("\t\tnav.style.width = \"1000px\";\r\n");
      out.write("\t\tmodalLogin.style.margin = \"0 0 0 53%\";\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tnav.style.width = \"1590px\";\r\n");
      out.write("\t\tmodalLogin.style.margin = \"0 0 0 69%\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tconsole.log('현재 주소 : ' + link);\r\n");
      out.write("\tconsole.log('현재 주소 : ' + mainAddress);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Train+One&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Do+Hyeon&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes fadein {\r\n");
      out.write("\t    from {\r\n");
      out.write("\t        opacity:0.1;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    to {\r\n");
      out.write("\t        opacity:1;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("@-webkit-keyframes fadein {\r\n");
      out.write("\t    from {\r\n");
      out.write("\t        opacity:0.1;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    to {\r\n");
      out.write("\t        opacity:1;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(".gallery_table {\r\n");
      out.write("\twidth: 1590px;\r\n");
      out.write("\ttable-layout: fixed;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmax-width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item_gallery {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tborder-radius: 0px;\r\n");
      out.write("\tdisplay: table-cell;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item_container {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel_img {\r\n");
      out.write("\twidth: 384px;\r\n");
      out.write("\tmin-height: 375px;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel_text {\r\n");
      out.write("\tpadding: 10px 0 10px 0;\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-size: 15pt;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel_title {\r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tcolor: #212121;\r\n");
      out.write("\tline-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotelName {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tcolor: #212121;\r\n");
      out.write("\tline-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotelAddress {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tcolor: #eb4d4b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel_des {\r\n");
      out.write("\tcolor: #636e72;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hotel_body {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_input_search {\r\n");
      out.write("\t/* background-image:url(https://cdn1.iconfinder.com/data/icons/hawcons/32/698627-icon-111-search-256.png); */\r\n");
      out.write("\tbackground-position: 13px center;\r\n");
      out.write("\tbackground-size: contain;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-color: transparent;\r\n");
      out.write("\tmargin-top: -30px;\r\n");
      out.write("\tmargin-bottom: 5%;\r\n");
      out.write("\t\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-bottom: 3px solid #f8585b;\r\n");
      out.write("\twidth: 390px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #28cae8;\r\n");
      out.write("\t/* text-indent: 60px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_input_search:focus {\r\n");
      out.write("\r\n");
      out.write("\t/* background-position: 0px center;\r\n");
      out.write("\ttext-indent: 0; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input::placeholder {\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".img-wrap {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-text {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blank {\r\n");
      out.write("\theight: 50vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img-wrap {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 95vh;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section {\r\n");
      out.write("\tmin-width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".king-section {\r\n");
      out.write("\twidth: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top {\r\n");
      out.write("\tmargin-bottom: 28%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-input {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-text {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-text-inner {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\t/* width: 1000px; */\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-blank {\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-blank2 {\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-blank3 {\r\n");
      out.write("\theight: 1000px;\r\n");
      out.write("\tmax-height: 40%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-blank4 {\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hidden {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*------------------------*/\r\n");
      out.write("\r\n");
      out.write("ul,li{ list-style: none; }\r\n");
      out.write("\r\n");
      out.write(".wrap{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrap1{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".wrap-in{ \r\n");
      out.write("    width: 1200px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_daddy4 {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0px;\r\n");
      out.write("    left: 0px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    /* display: none; */\r\n");
      out.write("    -webkit-box-align: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    -webkit-box-pack: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    z-index: 99;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write(".agree_daddy1 {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0px;\r\n");
      out.write("    left: 0px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    /* display: none; */\r\n");
      out.write("    -webkit-box-align: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    -webkit-box-pack: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    z-index: 99;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write(".agree_mom1 {\r\n");
      out.write("    margin: 120px auto;\r\n");
      out.write("    border-radius: 2px;\r\n");
      out.write("    width: 700px;\r\n");
      out.write("    background-color: rgb(255, 255, 255);\r\n");
      out.write("    z-index: 8;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("}\r\n");
      out.write(".agree_mom4 {\r\n");
      out.write("    margin: 120px auto;\r\n");
      out.write("    border-radius: 2px;\r\n");
      out.write("    width: 700px;\r\n");
      out.write("    background-color: rgb(255, 255, 255);\r\n");
      out.write("    z-index: 8;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_div {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_div_top {\r\n");
      out.write("    border-radius: 2px 2px 0px 0px;\r\n");
      out.write("    padding: 42px 42px 36px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_div_body {\r\n");
      out.write("    padding-top: 30px;\r\n");
      out.write("    padding-bottom: 42px;\r\n");
      out.write("    margin: 0px 42px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    display: block;\r\n");
      out.write("    -webkit-box-align: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    border-top: 1px solid rgb(238, 238, 238);\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_title {\r\n");
      out.write("    font-size: 26px;\r\n");
      out.write("    line-height: 38px;\r\n");
      out.write("    padding-right: 48px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_x_button {\r\n");
      out.write("    line-height: 38px;\r\n");
      out.write("    top: 38px;\r\n");
      out.write("    right: 42px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_x4 {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    background: url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBmaWxsPSIjMjIyIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0xMy40NjYgMTJsNi4yMy02LjIzYTEuMDM2IDEuMDM2IDAgMTAtMS40NjYtMS40NjZMMTIgMTAuNTM0bC02LjIzLTYuMjNBMS4wMzYgMS4wMzYgMCAxMDQuMzA0IDUuNzdsNi4yMyA2LjIzLTYuMjMgNi4yM2ExLjAzNiAxLjAzNiAwIDEwMS40NjYgMS40NjZsNi4yMy02LjIzIDYuMjMgNi4yM2ExLjAzNSAxLjAzNSAwIDEwMS40NjYtMS40NjVMMTMuNDY2IDEyeiIvPjwvc3ZnPg==\") center center / cover no-repeat;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    padding: 15px 15px;\r\n");
      out.write("}\r\n");
      out.write(".agree_x1 {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    background: url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBmaWxsPSIjMjIyIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0xMy40NjYgMTJsNi4yMy02LjIzYTEuMDM2IDEuMDM2IDAgMTAtMS40NjYtMS40NjZMMTIgMTAuNTM0bC02LjIzLTYuMjNBMS4wMzYgMS4wMzYgMCAxMDQuMzA0IDUuNzdsNi4yMyA2LjIzLTYuMjMgNi4yM2ExLjAzNiAxLjAzNiAwIDEwMS40NjYgMS40NjZsNi4yMy02LjIzIDYuMjMgNi4yM2ExLjAzNSAxLjAzNSAwIDEwMS40NjYtMS40NjVMMTMuNDY2IDEyeiIvPjwvc3ZnPg==\") center center / cover no-repeat;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    padding: 15px 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("    border: 0px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    display: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_tbody {\r\n");
      out.write("    border: 1px solid rgb(238, 238, 238);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_tr {\r\n");
      out.write("    border-bottom: 1px solid rgb(238, 238, 238);\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_th {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    background-color: rgb(238, 238, 238);\r\n");
      out.write("    padding: 12px;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    color: rgba(68, 68, 68);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".agree_td {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    line-height: 18px;\r\n");
      out.write("    padding: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section a {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body style=\"margin: 0;\">\r\n");
      out.write("\t<div class=\"king-section\">\r\n");
      out.write("\t\t<div class=\"section top\">\r\n");
      out.write("\t\t\t<div class=\"img-wrap\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/main_img.jpg\"\r\n");
      out.write("\t\t\t\t\tstyle=\"animation: fadein 3s; -webkit-animation: fadein 3s; width: 100%;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"section-blank\"></div>\r\n");
      out.write("\t\t\t<div class=\"main-text\">\r\n");
      out.write("\t\t\t\t<div class=\"main-text-inner\">\r\n");
      out.write("\t\t\t\t\t<div data-aos=\"flip-left\" data-aos-duration=\"1000\" style=\"font-family: 'Train One', cursive; color: #f8585b; font-weight: bold; font-size: 50pt; text-align: center;\">stay,</div>\r\n");
      out.write("\t\t\t\t\t<div data-aos=\"flip-up\" data-aos-duration=\"1000\" style=\"font-family: 'Train One', cursive; color: #f8585b; font-weight: bold; font-size: 50pt; text-align: center; margin-left: 15px;\">what you want</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"section-blank2\"></div>\r\n");
      out.write("\t\t\t<div class=\"main-input\" data-aos=\"zoom-in\" data-aos-duration=\"500\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"main_input_search\" id=\"search\" onkeyup=\"filter()\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Where are you going?\" style=\"font-family: 'Black Han Sans', sans-serif; font-size: 21pt;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"background-color: #f8585b; width: 50px; height: 50px; border-radius: 100px; position: relative; margin-left: 450px;\r\n");
      out.write("\t\t\t\t\ttop: -85px; align-content: center; justify-content: center;\"><img style=\"width: 28px; margin: 12px 10px 0px 9px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/main-search-btn.png\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"search_result\">\r\n");
      out.write("\t\t\t\t\t<div class=\"hotel-list hotel-list-scroll\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"section-blank3\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"section\" style=\"position: relative;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div style=\"height: 210px; width: 1590px; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style=\"font-family: 'Noto Sans KR', sans-serif; font-size: 27pt; font-weight: bold;\">지역별 관광지</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.airbnb.co.kr/s/%EC%84%9C%EC%9A%B8/homes?place_id=ChIJzWXFYYuifDUR64Pq5LTtioU&refinement_paths%5B%5D=%2Fhomes&search_type=section_navigation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"display: flex;\"><img style=\"width: 65px; border-radius: 10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/seoul.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 15px 228px 0px 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><b>서울</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>차로 5시간 거리</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.airbnb.co.kr/s/%EB%8C%80%EA%B5%AC/homes?place_id=ChIJ1a3vsrjjZTURMC44oCngkro&refinement_paths%5B%5D=%2Fhomes&search_type=section_navigation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"display: flex;\"><img style=\"width: 65px; border-radius: 10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/daegu.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  style=\"margin: 15px 208px 0px 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><b>대구</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>차로 1.5시간 거리</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.airbnb.co.kr/s/%EC%9A%B8%EC%82%B0/homes?place_id=ChIJgd6y4osuZjURATHZM3P6g3A&refinement_paths%5B%5D=%2Fhomes&search_type=section_navigation\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"display: flex;\"><img style=\"width: 65px; border-radius: 10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/ulsan.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  style=\"margin: 15px 226px 0px 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><b>울산</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>차로 1시간 거리</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a herf=\"https://www.airbnb.co.kr/s/%EB%8C%80%EC%A0%84/homes?place_id=ChIJAWZKutdIZTURtdOKmJ3WltE&refinement_paths%5B%5D=%2Fhomes&search_type=section_navigation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"display: flex;\"><img style=\"width: 65px; border-radius: 10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/daejeon.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  style=\"margin: 15px 0px 0px 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><b>대전</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>차로 3.5시간 거리</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: flex; margin-top: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.airbnb.co.kr/s/%EB%B6%80%EC%82%B0%EA%B4%91%EC%97%AD%EC%8B%9C/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_dates%5B%5D=april&flexible_trip_dates%5B%5D=may&flexible_trip_lengths%5B%5D=weekend_trip&date_picker_type=calendar&query=%EB%B6%80%EC%82%B0%EA%B4%91%EC%97%AD%EC%8B%9C&place_id=ChIJNc0j6G3raDURpwhxJHTL2DU&source=structured_search_input_header&search_type=autocomplete_click\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"display: flex;\"><img style=\"width: 65px; border-radius: 10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/busan.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"margin: 15px 225px 0px 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><b>부산</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>차로 0시간 거리</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.airbnb.co.kr/s/%EC%9D%B8%EC%B2%9C/homes?place_id=ChIJR4ITliVveTURQmG3LJD9N30&refinement_paths%5B%5D=%2Fhomes&search_type=section_navigation\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"display: flex;\"><img style=\"width: 65px; border-radius: 10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/incheon.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  style=\"margin: 15px 206px 0px 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><b>인천</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>차로 5.5시간 거리</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.airbnb.co.kr/s/%EA%B4%91%EC%A3%BC/homes?place_id=ChIJr6f1ASOJcTURSPUlAe3S9AU&refinement_paths%5B%5D=%2Fhomes&search_type=section_navigation\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"display: flex;\"><img style=\"width: 65px; border-radius: 10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/gwangju.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  style=\"margin: 15px 212px 0px 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><b>광주</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>차로 3.5시간 거리</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://www.airbnb.co.kr/s/%EC%A0%9C%EC%A3%BC/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_dates%5B%5D=april&flexible_trip_dates%5B%5D=may&flexible_trip_lengths%5B%5D=weekend_trip&date_picker_type=calendar&source=structured_search_input_header&search_type=search_query\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"display: flex;\"><img style=\"width: 65px; border-radius: 10px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/jeju.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div  style=\"margin: 15px 0px 0px 15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><b>제주</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>비행기로 1시간 거리</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"section show-hotel\" style=\"position: relative;\">\r\n");
      out.write("\t\t\t<div class=\"gallery_table\" style=\"margin: 0 auto; align-content: center;\">\r\n");
      out.write("\t\t\t\t<p style=\"font-size: 30pt; font-weight: bold; font-family: 'Noto Sans KR', sans-serif; text-align: left;\">\r\n");
      out.write("\t\t\t\t\t<strong>Stays</strong>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"gallery_container\" style=\"text-align: left; width: 1600px;\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"section-blank4\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 하단 '광고성 정보수신동의' -->\r\n");
      out.write("\t<div class=\"wrap hidden\">\r\n");
      out.write("        <div class=\"wrap-in\">\r\n");
      out.write("            <div class=\"agree_daddy4\">\r\n");
      out.write("                <div class=\"agree_mom4\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"agree_div\">\r\n");
      out.write("                            <div class=\"agree_div_top\">\r\n");
      out.write("                                <div class=\"agree_title\">광고성정보수신동의</div>\r\n");
      out.write("                                <div class=\"agree_x_button\">\r\n");
      out.write("                                    <button class=\"agree_x4\"></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"agree_div_body\">\r\n");
      out.write("                                <table class=\"agree_table\">\r\n");
      out.write("                                    <tbody class=\"agree_tbody\">\r\n");
      out.write("                                        <tr rowspan=\"1\" class=\"agree_tr\">\r\n");
      out.write("                                            <th colspan=\"1\" class=\"agree_th\">개인정보 수집 및 이용목적</th>\r\n");
      out.write("                                            <td colspan=\"1\" class=\"agree_td\">JAVA의 서비스, 이벤트, 업데이트에 대한 광고성 정보 전송</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr rowspan=\"1\" class=\"agree_tr\">\r\n");
      out.write("                                            <th colspan=\"1\" class=\"agree_th\">수집 항목</th>\r\n");
      out.write("                                            <td colspan=\"1\" class=\"agree_td\">휴대 전화 번호, 이메일 주소</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr rowspan=\"1\" class=\"agree_tr\">\r\n");
      out.write("                                            <th colspan=\"1\" class=\"agree_th\">개인 정보 보유 및 이용기간</th>\r\n");
      out.write("                                            <td colspan=\"1\" class=\"agree_td\">회원정보 편집에서 동의를 해제할 수 있으며 해제시 폐기\r\n");
      out.write("                                                (단, 관계 법령의 규정에 의하여 보존할 필요가 있는 경우 관련 법령에 따라 보관)\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 하단 '위치정보수신동의' -->\r\n");
      out.write("    <div class=\"wrap1 hidden\">\r\n");
      out.write("        <!-- 전체 화면 -->\r\n");
      out.write("        <div class=\"wrap-in\">\r\n");
      out.write("            <!-- 모달부분 -->\r\n");
      out.write("            <div class=\"agree_daddy1\">\r\n");
      out.write("                <div class=\"agree_mom1\">\r\n");
      out.write("                    <div class=\"agree_div\">\r\n");
      out.write("                        <div class=\"agree_div_top\">\r\n");
      out.write("                            <div class=\"agree_title\">위치정보수신동의</div>\r\n");
      out.write("                            <div class=\"agree_x_button\">\r\n");
      out.write("                                <button class=\"agree_x1\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"agree_div_body\">\r\n");
      out.write("                            <table class=\"agree_table\">\r\n");
      out.write("                                <tbody class=\"agree_tbody\">\r\n");
      out.write("                                    <tr rowspan=\"1\" class=\"agree_tr\">\r\n");
      out.write("                                        <th colspan=\"1\" class=\"agree_th\">국내 숙소 이용규칙 동의</th>\r\n");
      out.write("                                        <td colspan=\"1\" class=\"agree_td\">\r\n");
      out.write("                                            * 각 숙박시설의 규정(규칙 및 약관 등)을 준수해야 합니다. 숙박시설 규정을 위반 시 입실 불가,\r\n");
      out.write("                                            퇴실 조치, 추가요금 등이 발생할 수 있으며, 이에 대한 모든 책임은 예약 및 이용 고객님에게 있으므로\r\n");
      out.write("                                            숙박시설의 이용규칙과 시설 현황을 반드시 확인하시기 바랍니다.<br><br>\r\n");
      out.write("                                            * 규정 내 이용 가능 인원을 초과할 경우, 이용 불가 통보 또는 초과 인원에 대한 추가 요금이 발생할 수\r\n");
      out.write("                                            있으며, 이에 대한 모든 책임은 예약자 및 이용 고객님에게 있습니다.<br><br>\r\n");
      out.write("                                            * 미성년자 투숙 시 청소년보호법 등 관계 법령에 따라 미성년자(만 19세 미만 청소년)의 경우 혼숙이 금지\r\n");
      out.write("                                            되며, 법정대리인 동행 없이 혼숙이 불가한 점 반드시 유의하여 주시길 바랍니다. 또한 해당 사유로 인하여\r\n");
      out.write("                                            현장에서 입실이 불가할 경우 취소 및 환불이 불가합니다.<br><br>\r\n");
      out.write("                                            * 각 숙박시설 정보는 예약을 위한 참고 자료입니다. 숙박시설 내 자체 변동이나 기타 사유로 인해 실제와\r\n");
      out.write("                                            차이가 있을 수 있으며, 이에 대해 (주)떠나볼까 는 책임을 지지 않습니다.<br><br>\r\n");
      out.write("                                            * 객실배정에 따른 요청사항(금연룸, 고층 등)은 숙박시설에 전달되나, 최종 반영 여부는 예약하신 숙박시설의\r\n");
      out.write("                                            결정사항이므로 (주)떠나볼까 에서 보장할 수 없는 사항임을 유의하여 주시기 바랍니다.\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                                <tfoot class=\"agree_tfoot\">\r\n");
      out.write("                                    <td colspan=\"2\">\r\n");
      out.write("                                        <em>위 서비스이용약관은 거부할 수 있으며, 거부할 경우 서비스 이용이 제한됩니다.</em>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tfoot>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("\t<footer style=\"height: 100%; color: #919191; background-color: #f7f7f7;\">\r\n");
      out.write("\t\t<div style=\"width: 100%; margin-bottom: 40px;\">\r\n");
      out.write("\t\t\t<div style=\"border-top: 1px solid #dadada; width: 100%; margin: 0 auto;\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer\" style=\"width: 1590px; margin: 0 auto;\">\r\n");
      out.write("\t\t\t<div class=\"footer_section\" style=\"display: flex; margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div style=\"margin-right: 500px; margin-left: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 11pt;\"><b>소개</b></div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">JAVA 이용 방법</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">뉴스룸</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">투자자 정보</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">JAVA 플러스</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">JAVA 비즈니스 프로그램</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">채용정보</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">창립자 편지</div><br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-right: 500px;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 11pt;\"><b>커뮤니티</b></div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">다양성 및 소속감</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">접근성</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">구호 인력을 위한 숙소</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">게스트 추천</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">JAVA.org</div><br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 11pt;\"><b>JAVA 지원</b></div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">JAVA 코로나 19 대응 방안</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">도움말 센터</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">예약 취소 옵션</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">JAVA 이웃 민원 지원</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"font-size: 10pt;\">신뢰와 안전</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agreeAd\" style=\"cursor: pointer; font-size: 10pt;\">광고성정보수신동의</div><br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agreeGps\" style=\"cursor: pointer; font-size: 10pt;\">위치정보수신동의</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"border-top: 1px solid #dadada; width: 100%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<div style=\"height: 40px;\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width: 1590px; margin: 0 auto;\">(주) JAVA는 통신판매 중개자로서 통신판매의 당사자가 아니며 상품의 예약, 이용 및 환불 등과 관련한 의무와 책임은 각 판매자에게 있습니다.</div>\r\n");
      out.write("\t\t\t\t<div style=\"height: 20px;\"></div>\r\n");
      out.write("\t\t\t\t<div>Copyright ⓒ JAVA All rights reserved.</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div style=\"height: 20px;\"></div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// 광고성정보수신동의 모달관리\r\n");
      out.write("\t\tagreeAd = document.querySelector('.agreeAd');\r\n");
      out.write("\t\twrap = document.querySelector('.wrap');\r\n");
      out.write("\t\tclose = document.querySelector('.agree_x4');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tagreeAd.onclick = function(){\r\n");
      out.write("\t\t\twrap.classList.remove('hidden');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tclose.onclick = function(){\r\n");
      out.write("\t\t\twrap.classList.add('hidden');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 위치정보수신동의 모달관리\r\n");
      out.write("\t\tagreeGps = document.querySelector('.agreeGps');\r\n");
      out.write("\t\twrap1 = document.querySelector('.wrap1');\r\n");
      out.write("\t\tclose1 = document.querySelector('.agree_x1');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tagreeGps.onclick = function(){\r\n");
      out.write("\t\t\twrap1.classList.remove('hidden');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tclose1.onclick = function(){\r\n");
      out.write("\t\t\twrap1.classList.add('hidden');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tAOS.init();\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction filter() {\r\n");
      out.write("\t\t\tlet search = document.getElementById(\"search\").value.toLowerCase();\r\n");
      out.write("\t\t\tlet hotelSection = document.getElementsByClassName(\"hotel-section\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (let i = 0; i < hotelSection.length; i++) {\r\n");
      out.write("\t\t\t\thotelName = hotelSection[i].getElementsByClassName(\"hotelName\");\r\n");
      out.write("\t\t\t\thotelAddress = hotelSection[i].getElementsByClassName(\"hotelAddress\");\r\n");
      out.write("\t\t\t\thotel_section = document.querySelector('.hotel-section');\r\n");
      out.write("\t\t\t\tconsole.log(hotelName);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (hotelName[0].innerHTML.toLowerCase().indexOf(search) != -1 || hotelAddress[0].innerHTML.toLowerCase().indexOf(search) != -1) {\r\n");
      out.write("\t\t\t\t\thotel_section.classList.remove('hidden');\r\n");
      out.write("\t\t\t\t\thotelSection[i].style.display = \"block\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\thotel_section.classList.add('hidden');\r\n");
      out.write("\t\t\t\t\thotelSection[i].style.display = \"none\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (hotelName[0].innerHTML.toLowerCase().indexOf(search) != 0 || hotelAddress[0].innerHTML.toLowerCase().indexOf(search) != 0) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\thotelSection[i].style.display = \"none\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/header.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f0);
        }
        do {
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          int evalDoAfterBody = _jspx_th_c_005fset_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/header.jsp(46,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty login }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div class=\"login-modal-section\">\r\n");
          out.write("\t\t\t\t<div class=\"modal-box\">\r\n");
          out.write("\t\t\t\t\t<div class=\"text-login\">Login</div>\r\n");
          out.write("\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t<img id=\"close_submenu\" height=\"24px\"\r\n");
          out.write("\t\t\t\t\t\t\tsrc=\"https://cdn.dailyhotel.com/ux/common-close-ic-gray@2x.png\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<div class=\"text-modal\">호텔자바에 회원가입하시고 다양한 혜택을 누리세요.</div>\r\n");
          out.write("\t\t\t\t<div class=\"btn-wrapper\">\r\n");
          out.write("\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\"><button class=\"modal-in-btn\">로그인</button></a>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/join\"><button class=\"modal-in-btn\">회원가입</button></a>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/header.jsp(68,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty login }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div class=\"login-modal-section\">\r\n");
          out.write("\t\t\t\t<div class=\"modal-box\">\r\n");
          out.write("\t\t\t\t\t<div class=\"text-login\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/myPage\" style=\"color: black;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.cu_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" 님</a></div>\r\n");
          out.write("\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t<img id=\"close_submenu\" height=\"24px\"\r\n");
          out.write("\t\t\t\t\t\t\tsrc=\"https://cdn.dailyhotel.com/ux/common-close-ic-gray@2x.png\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<div class=\"text-modal\">자바호텔에 오신걸 환영합니다.</div>\r\n");
          out.write("\t\t\t\t<div class=\"btn-wrapper\">\r\n");
          out.write("\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/modify\"><button class=\"modal-in-btn\">정보수정</button></a>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\"><button class=\"modal-in-btn\">로그아웃</button></a>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/dailyMain.jsp(391,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      // /WEB-INF/views/dailyMain.jsp(391,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/dailyMain.jsp(391,6) '${map.list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${map.list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"hotel-section hidden\"><!-- hidden -->\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"hotel-section-info\" style=\"width: 420px; background-color: rgba( 255, 255, 255, 0.5 ); margin: 0 auto;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/hotelView/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.HO_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<strong class=\"hotelName\" style=\"font-weight: 600;\">\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.HO_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"</strong>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"hotelAddress\">'");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.HO_ADDRESS }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<span class=\"hotel_body\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"hotel_des\" style=\"margin-top:5px; height: 55px; width: 350px; margin: 0 auto;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<span style=\"word-break: break-all;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.HO_DESCRIPTION }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/dailyMain.jsp(531,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("map");
      // /WEB-INF/views/dailyMain.jsp(531,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/dailyMain.jsp(531,5) '${map.list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${map.list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<div class=\"item_gallery\" style=\"padding: 0; margin-right: 25px; margin-bottom: 16px; width: 370px; display: inline-block;\">\r\n");
            out.write("\t\t\t\t\t\t\t<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/hotelView/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.HO_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/\" class=\"item_container\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"hotel_img\" class=\"content\" style=\"background-image: url(http://182.212.181.172:9000/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.HO_UPLOADFILE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\"></div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"hotel_text\" style=\"width: 286px;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.HO_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
